# Generated by Django 2.1.2 on 2018-12-09 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='date_uploaded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
