# Generated by Django 2.1.2 on 2018-12-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20181211_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=250),
        ),
    ]
