# Generated by Django 2.1.2 on 2018-12-11 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20181211_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_file', models.FileField(upload_to='')),
                ('genre', models.CharField(default='No genre', max_length=100)),
                ('music_logo', models.FileField(blank=True, null=True, upload_to='')),
                ('date_uploaded', models.DateField(default=django.utils.timezone.now)),
                ('file_type', models.CharField(default='No file type', max_length=10)),
                ('music_title', models.CharField(default='No song title', max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
