# Generated by Django 2.1.2 on 2018-12-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20181211_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='music',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='music',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='music',
            name='music_file',
        ),
        migrations.RemoveField(
            model_name='music',
            name='music_logo',
        ),
        migrations.RemoveField(
            model_name='music',
            name='music_title',
        ),
        migrations.AddField(
            model_name='music',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='music',
            name='video_genre',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='video_title',
            field=models.CharField(default=True, max_length=500),
            preserve_default=False,
        ),
    ]
