# Generated by Django 2.1.2 on 2018-12-15 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20181215_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videofile',
            new_name='video_file',
        ),
    ]
