# Generated by Django 2.1.2 on 2018-12-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20181215_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=True, upload_to='videos'),
            preserve_default=False,
        ),
    ]
