# Generated by Django 2.1.2 on 2019-01-06 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20181217_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='artist',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
