# Generated by Django 2.1.2 on 2019-01-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20190107_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
    ]
