# Generated by Django 2.1.2 on 2019-03-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(default='audios', upload_to=''),
        ),
    ]
