# Generated by Django 2.1.2 on 2019-04-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20190318_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_favorite',
        ),
    ]
