# Generated by Django 2.1.2 on 2019-04-03 15:19

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_remove_video_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='No video'),
            preserve_default=False,
        ),
    ]
