# Generated by Django 2.1.2 on 2019-06-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20190403_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.AlterField(
            model_name='video',
            name='video_logo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
