# Generated by Django 2.1.2 on 2019-06-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_auto_20190625_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
    ]
