# Generated by Django 2.1.2 on 2019-06-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_remove_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
