# Generated by Django 2.1.2 on 2019-06-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_auto_20190627_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(max_length=500, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_logo',
            field=models.FileField(max_length=500, null=True, upload_to='videos/'),
        ),
    ]
