# Generated by Django 2.1.2 on 2019-06-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_logo',
        ),
    ]
