# Generated by Django 2.1.2 on 2019-06-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0028_remove_video_video_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='user',
        ),
        migrations.RemoveField(
            model_name='view',
            name='video',
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
