# Generated by Django 2.1.2 on 2019-07-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_auto_20190628_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AddField(
            model_name='video',
            name='publication_date',
            field=models.DateField(default=0.0),
        ),
    ]
