# Generated by Django 2.1.2 on 2019-07-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_auto_20190714_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.RemoveField(
            model_name='video',
            name='publication_date',
        ),
    ]
